package com.xtremelabs.imageutils;

public enum ImageRequestType {
	DEFAULT, PRECACHE_TO_DISK, PRECACHE_TO_MEMORY, ADAPTER_REQUEST, PRECACHE_TO_DISK_FOR_ADAPTER, PRECACHE_TO_MEMORY_FOR_ADAPTER, DEPRIORITIZED_FOR_ADAPTER
}