package com.xtremelabs.imageutils;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

import com.xtremelabs.imageutils.db.Table;

class ImagesTable extends Table<ImageEntry> {

	private static final String TABLE_NAMES = "images";

	// must remain in same order as Columns enum
	private static final String[] COLUMNS = {
		"_id",
		"uri",
		"on_disk",
		"creation_time",
		"last_accessed_time",
		"size_x",
		"size_y",
		"fileSize" };

	enum Columns {
		ID(0),
		URI(1),
		ON_DISK(2),
		CREATION_TIME(3),
		LAST_ACCESSED_TIME(4),
		SIZE_X(5),
		SIZE_Y(6),
		FILE_SIZE(7);

		private final int mIndex;

		private Columns(int index) {
			mIndex = index;
		}

		String getName() {
			return COLUMNS[mIndex];
		}
	}

	private static class InstanceHolder {
		private static ImagesTable sInstance = new ImagesTable();
	}

	static ImagesTable getInstance() {
		return InstanceHolder.sInstance;
	}

	@Override
	public String[] getColumns() {
		return COLUMNS;
	}

	@Override
	public String getTableName() {
		return TABLE_NAMES;
	}

	@Override
	protected String getColumnsForCreation() {
		String columns = COLUMNS[0] + " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMNS[1] + " TEXT, " + COLUMNS[2] + " INTEGER, " + COLUMNS[3] + " INTEGER, " + COLUMNS[4] + " INTEGER, " + COLUMNS[5]
				+ " INTEGER, " + COLUMNS[6] + " INTEGER, " + COLUMNS[7] + " INTEGER, ";
		return columns;
	}

	@Override
	protected String getUniqueString() {
		return COLUMNS[1];
	}

	@Override
	protected ContentValues toContentValues(ImageEntry item) {
		ContentValues contentValues = new ContentValues();
		// id is generated by DB, not model
		contentValues.put(COLUMNS[1], item.uri);
		contentValues.put(COLUMNS[2], item.onDisk ? 1 : 0);
		contentValues.put(COLUMNS[3], item.creationTime);
		contentValues.put(COLUMNS[4], item.lastAccessedTime);
		contentValues.put(COLUMNS[5], item.sizeX);
		contentValues.put(COLUMNS[6], item.sizeY);
		contentValues.put(COLUMNS[7], item.fileSize);
		return contentValues;
	}

	public ImageEntry getEntry(SQLiteDatabase db, String uri) {
		ImageEntry entry = null;

		Cursor cursor = selectFromTable(db, Columns.URI.getName() + "=?", new String[] { uri });
		if (cursor.moveToFirst()) {
			entry = getEntryFromCursor(cursor);
		}
		return entry;
	}

	public static ImageEntry getEntryFromCursor(Cursor cursor) {
		ImageEntry entry = new ImageEntry();
		entry.id = cursor.getLong(0);
		entry.uri = cursor.getString(1);
		entry.creationTime = cursor.getLong(2);
		entry.lastAccessedTime = cursor.getLong(3);
		entry.onDisk = cursor.getInt(4) == 1;
		entry.sizeX = cursor.getInt(5);
		entry.sizeY = cursor.getInt(6);
		entry.fileSize = cursor.getLong(7);
		return entry;
	}
}
